assets_base_url: "/2017annualreport"
title: Your awesome title
email: your-email@domain.com
description: CIGI Annual Report
baseurl: "/2017annualreport"
url: "https://cigihub.github.io"

# Build settings
markdown: kramdown
gems:
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - jsconfig.json
  - .browserslistrc
  - js
  - yarn.lock
  - .gitignore
  - deploy.js
  - webpack.config.dev.js
  - webpack.config.prod.js
assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache_type: memory
  prefix: "/assets"
  autoprefixer:
    flexbox: no-2009
