assets_base_url: "/"
title: CIGI 2017 Annual Report
email: websiteupdates@cigionline.org
description: CIGI Annual Report
baseurl: "/interactives/2017annualreport"
url: "https://staging.cigionline.org"

# Build settings
markdown: kramdown
gems:
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - jsconfig.json
  - .browserslistrc
  - js
  - utils
  - yarn.lock
  - .gitignore
  - deploy.js
  - webpack.config.dev.js
  - webpack.config.prod.js
assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache_type: memory
  prefix: "/assets"
  autoprefixer:
    flexbox: no-2009
