# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  CIGI Annual Report
baseurl: "/cigi" # the subpath of your site, e.g. /blog
url: "https://rangle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - .gitignore
  - deploy.js
assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache_type: memory
  prefix: "/assets"
  autoprefixer:
    flexbox: no-2009
    browsers:
      - "last 1 Chrome version"
      - "last 1 Firefox version"
      - "last 1 Edge version"
      - "last 1 Opera version"
      - "last 1 Safari version"
      - "last 1 ie version"
